README.md, platformio.ini, src/NerdMinerV2.ino.cpp, src/wManager.cpp, src/wManager.h
- Adding the possibility to rotate and turn the screen on and off
- Refactoring of the "configuration reset" button
=> Buttons review

src/monitor.cpp
Added pool url and days, hours:minutes:seconds to main screen.
=> added pool url and days, hours:minutes:seconds to main screen.

src/stratum.cpp
Use c_str(), since sprintf expects a C-string here
=> Fix mining submit code

src/NerdMinerV2.ino.cpp, src/mining.cpp, src/mining.h, src/stratum.cpp, src/stratum.h, src/utils.cpp
=> Essential Nerdminer code rework

src/mining.cpp, src/utils.cpp
Diff target needs to be converted to little endian for comparison.
=> Fix checkValid function

src/monitor.cpp
Small code refactoring to avoid code duplication
=> getTime function code refactoring

src/monitor.cpp
I found out that the sum of the total hashrate is wrong. I fixed it by limiting the size of the JSON received from the pool.
=> Fixed wrong pool total hashrate, with jsonfilter

README.md, lib/TFT_eSPI/User_Setup_Select.h, lib/TFT_eSPI/User_Setups/Setup212_ESP32Cam_DongleDisplay.h, platformio.ini, src/NerdMinerV2.ino.cpp, src/drivers/devices/esp32CAM.h, src/drivers/displays/dongleDisplayDriver.cpp, src/drivers/storage/SDCard.cpp, src/drivers/storage/SDCard.h, src/drivers/storage/nvMemory.cpp, src/drivers/storage/nvMemory.h, src/drivers/storage/storage.h, src/mining.cpp, src/wManager.cpp
Hello, 
i reverted the keys for saving data to SPIFFS for compatibility reasons, fixed the timezone bug, added SPI access for SD cards to use them along side a Display (not tested, with displays acccessed using DMA), as well as some minor changes.
=> SPI support for SD card access, display for esp32cam, minor changes.

src/drivers/displays/displayDriver.h, src/drivers/storage/SDCard.cpp, src/drivers/storage/SDCard.h, src/drivers/storage/nvMemory.cpp, src/drivers/storage/nvMemory.h
Fix build for MacOS and Linux.
=> Fix build for MacOS and Linux.

README.md
Basically this PR introduces:
- Linted readme.md file
- Add link to public-pool repo
- Add description about how to add a custom worker name for specific public-pool
- Add todo for password
=> Improved doc with custom worker

README.md
Following issue #241 clarifies that it is best to use Google Chrome in incognito mode.
=> Tips for online flash

README.md
A very simple PR to introduce in useful link.
=> Add link to Online ESP Tool

README.md
=> Fix two links

platformio.ini, src/drivers/devices/device.h, src/drivers/devices/esp32S3MiniWeact.h, src/drivers/devices/esp32S3MiniWemos.h
support cheap s3 mini devices
tested on weact s3 mini => 79.76 KH/s and working RGB led
=> feat : support s3 mini devices

.gitignore
=> added ignore for jetbrains/clion directory

src/drivers/displays/amoledDisplayDriver.cpp, src/drivers/displays/dongleDisplayDriver.cpp, src/drivers/displays/esp23_2432s028r.cpp, src/drivers/displays/m5stickCDriver.cpp, src/drivers/displays/rotation.h, src/drivers/displays/tDisplayDriver.cpp, src/drivers/displays/tDisplayV1Driver.cpp, src/drivers/displays/t_qtDisplayDriver.cpp
This helps clarify what `lcd_setRotation(1)` means without having to refer to ChatGPT.
=> added consts for display rotation for clarification

README.md
I have listed in the table the correct domain, port and also who is currently maintaining the project.
=> Details of Pool nerdminers.org

src/utils.cpp
I was trying to modify the getNextExtranonce2 function to have a random nonce and like the code I made
It was a little better than the code that was before (I believe), I decided to create a merge while maintaining the function
original with the modification and I also created a getRandomExtranonce2 function that can be used in the future or even
make the change through some configuration
=> Improvement getNextExtranonce2 and create getRandomExtranonce2

README.md, platformio.ini, src/drivers/devices/lilygoT_HMI.h, src/drivers/displays/t_hmiDisplayDriver.cpp, src/monitor.cpp, src/monitor.h
1/ Enable battery option
2/ Improve pool data api URL discovery based on Settings.PoolAddress and/or Settings.PoolPort
it is possible that this is applicable to ESP32_2432S028R || ESP32_2432S028_2USB || ESP32_2432S024 || NERDMINER_T_HMI
=> t-hmi model improvements and bugfixes

platformio.ini, src/NerdMinerV2.ino.cpp
support sdcard on esp32 s3 geek
fixes #405
=> feat : add support to esp32 s3 geek using sdcard fixes #405

platformio.ini, src/NerdMinerV2.ino.cpp, src/drivers/devices/esp322432s028r.h, src/drivers/displays/esp23_2432s028r.cpp, src/drivers/storage/SDCard.cpp, src/drivers/storage/SDCard.h, src/drivers/storage/nvMemory.cpp, src/drivers/storage/storage.h, src/monitor.cpp, src/monitor.h, src/wManager.cpp
Color inversion as a parameter in settings;
WIFIManager adjustments;
Memory fine tuning (inconsistent sprite creation);
Price text size adjust;
Testnet banner if pointing to tn.vkbit.com;
SDCard tested and adjusted.
=> Solution to the odd colors in new boards version (work on any variant), and some improvements.

auto_firmware_version.py, platformio.ini, src/drivers/displays/wt32DisplayDriver.cpp
add firmware name based on tag name and commit hash, this name is available in the code as a predefined constant
=> add automagic firmware version name 

platformio.ini, src/drivers/displays/dongleDisplayDriver.cpp
=> feat : start s3 dongle without screen on and back screen functions if BL is off

src/monitor.cpp, src/monitor.h
Conseguir una mejor actualización del precio de bitcoin, cambiando la api de lectura
Get a better bitcoin price update by changing the reading api
all credits for https://github.com/ChimpRocket
=> Update correctly the bitcoin price

README.md
Add ESP32 C3/S3 0.24 Inch OLED Affiliate links on README.md
Release this PR https://github.com/BitMaker-hub/NerdMiner_v2/pull/545
=> docs: add ESP32 C3/S3 0.24 Inch OLED Affiliate links on README.md
